//
// Created by SebastianZiółkowski on 23.11.2019.
//

#ifndef LICENCJATPROGRAM_CONSTVARIABLE_H
#define LICENCJATPROGRAM_CONSTVARIABLE_H

#define MAX_BUFFER_SIZE 127
#define MAX 10
#define MIN 1

#endif //LICENCJATPROGRAM_CONSTVARIABLE_H
